# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taylor LeCroy | Product Designer & Creative Director
email: taylorlecroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a designer working remotely
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taylorlecroy.com" # the base hostname & protocol for your site
currentPosition: CURRENT - Product Designer at Olark

# Build settings
markdown: kramdown
